# Generated by Django 6.0 on 2026-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnemos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileasset",
            name="file",
            field=models.FileField(upload_to="mnemos/%Y/%m/"),
        ),
    ]
