# Generated by Django 6.0 on 2026-01-28 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("mnemos", "0003_aiartifact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiartifact",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="fileasset",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="fileattachment",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="aiartifact",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="mnemos_aiar_content_f8ac4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiartifact",
            index=models.Index(
                fields=["artifact_type", "-created_at"],
                name="mnemos_aiar_artifac_468d3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["-created_at"], name="mnemos_file_created_15321f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["original_name"], name="mnemos_file_origina_03be57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="mnemos_file_content_85b61a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["-created_at"], name="mnemos_file_created_c11383_idx"
            ),
        ),
    ]
