# Generated by Django 6.0.6 on 2026-08-10 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atlas", "0007_backuprun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Usually the customer/org name.", max_length=200
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "github_orgs",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One GitHub org/user login per line. Searches every public repo they own.",
                    ),
                ),
                (
                    "github_repos",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One owner/name per line, for targeted checks.",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One per line: company name, internal domains, project codenames.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "notify_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Where new findings are sent. Blank = no email.",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloud_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: the specific app this exposure check covers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_profiles",
                        to="atlas.cloudproject",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Atlas customer this profile belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_profiles",
                        to="atlas.cloudcredential",
                    ),
                ),
                (
                    "github_installation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Use this installation's token for API calls. Falls back to settings.AEGIS_GITHUB_TOKEN.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_profiles",
                        to="atlas.githubinstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("code_search", "GitHub code search"),
                            ("gharchive", "GH Archive stream"),
                        ],
                        default="code_search",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("ok", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("queries_run", models.PositiveIntegerField(default=0)),
                (
                    "queries_skipped",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Dropped by the per-run query cap — surfaced, never silent.",
                    ),
                ),
                ("files_examined", models.PositiveIntegerField(default=0)),
                ("findings_new", models.PositiveIntegerField(default=0)),
                ("findings_seen", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True, default="")),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="aegis.watchprofile",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Exposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("repo_full_name", models.CharField(db_index=True, max_length=300)),
                ("file_path", models.CharField(blank=True, default="", max_length=700)),
                ("url", models.URLField(blank=True, default="", max_length=900)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("code_search", "GitHub code search"),
                            ("gharchive", "GH Archive stream"),
                        ],
                        default="code_search",
                        max_length=20,
                    ),
                ),
                ("detector", models.CharField(db_index=True, max_length=60)),
                (
                    "detector_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "matched_keyword",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "redacted_snippet",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Redacted preview. The raw secret is never persisted.",
                        max_length=500,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=400)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("false_positive", "False positive"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("times_seen", models.PositiveIntegerField(default=1)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="aegis.watchprofile",
                    ),
                ),
                (
                    "first_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_findings",
                        to="aegis.watchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["profile", "status", "severity"],
                        name="aegis_expos_profile_a8587b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "fingerprint"),
                        name="aegis_exposure_unique_per_profile",
                    )
                ],
            },
        ),
    ]
