# Generated by Django 6.0.6 on 2026-08-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aegis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchprofile",
            name="repo_denylist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One substring per line. Repos whose full name matches are dropped. Use for dataset/crawler repos that mention every domain on the internet. Added to settings.AEGIS_DEFAULT_REPO_DENYLIST.",
            ),
        ),
        migrations.AddField(
            model_name="watchprofile",
            name="search_globally",
            field=models.BooleanField(
                default=False,
                help_text="Also search ALL of public GitHub for these keywords, not just the orgs/repos above. This is how you find a leak in a contractor's personal repo — the case scoped search can never catch.",
            ),
        ),
    ]
