# Generated by Django 6.0.6 on 2026-08-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aegis", "0002_watchprofile_repo_denylist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exposure",
            name="triage_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why this was dismissed or accepted. Shown verbatim in the customer report — the explanation IS the deliverable, so write it for them.",
                max_length=400,
            ),
        ),
        migrations.AddField(
            model_name="watchprofile",
            name="posture",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="watchprofile",
            name="posture_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
