# Generated by Django 6.0 on 2025-12-21 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable key used by other modules, e.g. janus_gate_summary",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "consumer",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("janus", "Janus"),
                            ("okr", "OKR"),
                            ("sites", "Site Builder"),
                            ("code", "Code Analyzer"),
                        ],
                        default="general",
                        max_length=24,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags (MVP)",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("input_json", models.JSONField(default=dict)),
                ("require_substrings", models.JSONField(blank=True, default=list)),
                ("require_json", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="athena.prompttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("goal", models.TextField(blank=True)),
                ("context", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "output_contract",
                    models.TextField(
                        blank=True,
                        help_text="Expected output shape, JSON schema, headings, etc.",
                    ),
                ),
                ("tone", models.TextField(blank=True)),
                ("guardrails", models.TextField(blank=True)),
                (
                    "body",
                    models.TextField(
                        help_text="The actual prompt template text. Use {{ var_name }} placeholders."
                    ),
                ),
                ("changelog", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="athena.prompttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("template", "version")},
            },
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="approved_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="athena.promptversion",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_current_for",
                to="athena.promptversion",
            ),
        ),
        migrations.CreateModel(
            name="PromptRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rendered_prompt", models.TextField(blank=True)),
                ("output_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")],
                        default="pass",
                        max_length=8,
                    ),
                ),
                ("check_results", models.JSONField(blank=True, default=dict)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="athena.prompttemplate",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="athena.prompttestcase",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="athena.promptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Variable name used in prompt, e.g. project_name",
                        max_length=80,
                    ),
                ),
                (
                    "var_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("bool", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("default_value", models.TextField(blank=True)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="athena.prompttemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "name")},
            },
        ),
    ]
