# Generated by Django 6.0 on 2025-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptversion",
            name="auto_compose",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, body is composed from structured fields.",
            ),
        ),
    ]
