# Generated by Django 6.0 on 2025-12-25 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0003_athenamodelsettings_athenathread_athenastudiorun_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppContextSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable key e.g. nurbai_produce", max_length=80
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human name e.g. Nurbai Produce App", max_length=160
                    ),
                ),
                (
                    "app_path",
                    models.CharField(
                        help_text="Filesystem path e.g. /nurbai/apps/produce",
                        max_length=300,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Monotonic version per key"
                    ),
                ),
                ("source", models.CharField(default="code_analyzer", max_length=40)),
                ("snapshot_json", models.JSONField(blank=True, default=dict)),
                ("description_md", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_approved_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key", "version"], name="athena_appc_key_5d2683_idx"
                    ),
                    models.Index(
                        fields=["key", "is_approved"], name="athena_appc_key_841c61_idx"
                    ),
                ],
                "unique_together": {("key", "version")},
            },
        ),
    ]
