# Generated by Django 6.0 on 2026-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0004_appcontextsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptversion",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="The actual prompt template text. Use {{ var_name }} placeholders.",
            ),
        ),
    ]
