# Generated by Django 6.0 on 2026-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0005_alter_promptversion_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="athenathread",
            name="last_design_doc",
            field=models.TextField(blank=True, default=""),
        ),
    ]
