# Generated by Django 6.0 on 2026-01-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0006_athenathread_last_design_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="athenathread",
            name="mode",
            field=models.CharField(
                choices=[("enhancement", "Enhancement"), ("new_app", "New App")],
                default="enhancement",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="athenathread",
            name="ui_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
