# Generated by Django 6.0 on 2026-06-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0007_athenathread_mode_athenathread_ui_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("feature_designer", "Feature Designer"),
                    ("app_builder", "App Builder"),
                    ("impl_generator", "Implementation Generator"),
                ],
                db_index=True,
                default="none",
                help_text="Functional slot in the Studio pipeline (feature designer, app builder, impl generator).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="athenamodelsettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("echo", "Echo (dev)"),
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("azure_openai", "Azure OpenAI"),
                    ("local", "Local"),
                ],
                default="echo",
                max_length=24,
            ),
        ),
    ]
