# Generated by Django 6.0.6 on 2026-09-10 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0009_seed_default_prompts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("context", "Context (CLAUDE.md)"),
                            ("design_doc", "Design doc"),
                        ],
                        default="context",
                        max_length=16,
                    ),
                ),
                ("target_path", models.CharField(max_length=700)),
                ("bytes_written", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_context_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_exports",
                        to="athena.appcontextsnapshot",
                    ),
                ),
                (
                    "studio_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_exports",
                        to="athena.athenastudiorun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["snapshot", "-created_at"],
                        name="athena_cont_snapsho_5b1c56_idx",
                    )
                ],
            },
        ),
    ]
