# Generated by Django 6.0.6 on 2026-09-10 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0010_contextexport"),
        ("atlas", "0007_backuprun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_path", models.CharField(max_length=700)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "brief_path",
                    models.CharField(blank=True, default="", max_length=700),
                ),
                ("command", models.TextField(blank=True, default="")),
                ("log", models.TextField(blank=True, default="")),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-run override; blank = settings default.",
                        null=True,
                    ),
                ),
                ("branch", models.CharField(blank=True, default="", max_length=200)),
                (
                    "base_commit",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "result_commit",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("diff_stat", models.TextField(blank=True, default="")),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cloud_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="atlas.cloudproject",
                    ),
                ),
                (
                    "context_export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="athena.contextexport",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="athena.appcontextsnapshot",
                    ),
                ),
                (
                    "studio_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="athena.athenastudiorun",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="athena.prompttemplate",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="athena.athenathread",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athena_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="athena.promptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="athena_agen_status_df59c5_idx",
                    ),
                    models.Index(
                        fields=["thread", "-started_at"],
                        name="athena_agen_thread__bc3a9a_idx",
                    ),
                ],
            },
        ),
    ]
