# Generated by Django 6.0.6 on 2026-09-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athena", "0011_agentrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="merge_commit",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="merged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="merged_into",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
