# Generated by Django 6.0 on 2025-12-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Short description used as seed for GPT."
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Canonical domain, e.g. https://example.com (optional)",
                        max_length=255,
                    ),
                ),
                ("max_depth", models.PositiveIntegerField(default=3)),
                ("max_children_per_page", models.PositiveIntegerField(default=3)),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(blank=True, max_length=20)),
                ("secondary_color", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="sites_builder.developer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("ftp", "FTP"), ("local", "Local folder")],
                        default="ftp",
                        max_length=20,
                    ),
                ),
                ("ftp_host", models.CharField(blank=True, max_length=255)),
                ("ftp_username", models.CharField(blank=True, max_length=255)),
                ("ftp_password", models.CharField(blank=True, max_length=255)),
                (
                    "ftp_remote_root",
                    models.CharField(
                        blank=True,
                        help_text="Remote root path, e.g. /public_html/myclient",
                        max_length=255,
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        help_text="Absolute path on server to copy files to for LOCAL deployment.",
                        max_length=512,
                    ),
                ),
                ("is_default", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_targets",
                        to="sites_builder.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("depth", models.PositiveIntegerField(default=0)),
                ("is_root", models.BooleanField(default=False)),
                ("body_html", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=512)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                ("schema_jsonld", models.TextField(blank=True)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="sites_builder.page",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="sites_builder.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "slug")},
            },
        ),
    ]
