# Generated by Django 6.0 on 2025-12-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="hero_image_url",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
