# Generated by Django 6.0 on 2025-12-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0002_page_hero_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=20,
            ),
        ),
    ]
