# Generated by Django 6.0 on 2025-12-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0003_site_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
