# Generated by Django 6.0 on 2025-12-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0004_alter_site_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
