# Generated by Django 6.0 on 2025-12-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0005_alter_page_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="If set, this page will not be auto-regenerated.",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="manual_html",
            field=models.TextField(
                blank=True,
                help_text="Optional manual HTML override when the page is locked.",
                null=True,
            ),
        ),
    ]
