# Generated by Django 6.0 on 2025-12-27 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0006_page_is_locked_page_locked_at_page_locked_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAuditRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("start_url", models.URLField(blank=True)),
                ("pages_scanned", models.PositiveIntegerField(default=0)),
                ("links_checked", models.PositiveIntegerField(default=0)),
                ("broken_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_runs",
                        to="sites_builder.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteAuditIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("target_url", models.URLField()),
                ("link_type", models.CharField(blank=True, max_length=50)),
                ("is_internal", models.BooleanField(default=False)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="sites_builder.siteauditrun",
                    ),
                ),
            ],
        ),
    ]
