# Generated by Django 6.0 on 2026-01-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0007_siteauditrun_siteauditissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="structure_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="site",
            name="target_page_count",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
