# Generated by Django 6.0 on 2026-01-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0008_site_structure_locked_site_target_page_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="ia_plan",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="ia_planned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
