# Generated by Django 6.0 on 2026-01-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0009_site_ia_plan_site_ia_planned_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ("nav_order", "title", "id")},
        ),
        migrations.AddField(
            model_name="page",
            name="nav_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Controls menu ordering. Lower comes first."
            ),
        ),
    ]
