# Generated by Django 6.0 on 2026-01-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0010_alter_page_options_page_nav_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="theme_css",
            field=models.CharField(
                choices=[("neon_glass", "Neon Glass"), ("minimal", "Minimal")],
                default="neon_glass",
                help_text="Select the source theme stylesheet to copy into assets/css/site.css",
                max_length=50,
            ),
        ),
    ]
