# Generated by Django 6.0 on 2026-01-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0013_alter_site_theme_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="ga4_measurement_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="ga4_property_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
