# Generated by Django 6.0 on 2026-01-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0015_alter_site_theme_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="theme_css",
            field=models.CharField(
                choices=[
                    ("neon_glass", "Neon Glass"),
                    ("minimal", "Minimal"),
                    ("startup", "Startup Modern"),
                    ("aurora", "Aurora"),
                    ("verdant", "Verdant"),
                    ("bauhaus", "Bauhaus"),
                ],
                default="neon_glass",
                help_text="Select the source theme stylesheet to copy into assets/css/site.css",
                max_length=50,
            ),
        ),
    ]
