# Generated by Django 6.0 on 2026-01-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0017_evergreenarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="evergreenarticle",
            name="cornerstone",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a supporting article, link it to its cornerstone.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporting_articles",
                to="sites_builder.evergreenarticle",
            ),
        ),
        migrations.AddField(
            model_name="evergreenarticle",
            name="is_cornerstone",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ArticleCornerstoneLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("anchor_text", models.CharField(blank=True, max_length=140)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cornerstone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cornerstone_links",
                        to="sites_builder.evergreenarticle",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_cornerstone_links",
                        to="sites_builder.site",
                    ),
                ),
                (
                    "supporting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_links",
                        to="sites_builder.evergreenarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "id"],
                "unique_together": {("cornerstone", "supporting")},
            },
        ),
    ]
