# Generated by Django 6.0 on 2026-01-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0018_evergreenarticle_cornerstone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evergreenarticle",
            name="cornerstone",
        ),
    ]
