# Generated by Django 6.0 on 2026-01-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0019_remove_evergreenarticle_cornerstone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evergreenarticle",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="evergreenarticle",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="evergreenarticle",
            constraint=models.UniqueConstraint(
                fields=("site", "slug"), name="uniq_site_article_slug"
            ),
        ),
    ]
