# Generated by Django 6.0 on 2026-01-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0020_alter_evergreenarticle_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTopNavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "url",
                    models.CharField(
                        help_text="Relative link like 'about-us.html' or absolute like 'https://...'",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_cta", models.BooleanField(default=False)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_nav_items",
                        to="sites_builder.site",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "label", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "label", "url"),
                        name="uniq_site_topnav_label_url",
                    )
                ],
            },
        ),
    ]
