# Generated by Django 6.0 on 2026-06-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0021_sitetopnavitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="landing_sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Landing pages only: ordered section blocks (hero, stats, features, cards, cta, richtext).",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("article", "Article (editorial)"),
                    ("landing", "Landing (marketing)"),
                ],
                default="article",
                help_text="Article = editorial single-column; Landing = composed marketing sections.",
                max_length=20,
            ),
        ),
    ]
