# Generated by Django 6.0 on 2026-06-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0022_page_landing_sections_page_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="nav_cta_label",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="site",
            name="nav_cta_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
