# Generated by Django 6.0 on 2026-07-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0024_alter_site_theme_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="footer_links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
