# Generated by Django 6.0.6 on 2026-07-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_builder", "0025_site_footer_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymenttarget",
            name="cf_project_name",
            field=models.CharField(
                blank=True,
                help_text="Cloudflare Pages project name for CF_PAGES deployment, e.g. gym2x.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="deploymenttarget",
            name="type",
            field=models.CharField(
                choices=[
                    ("ftp", "FTP"),
                    ("local", "Local folder"),
                    ("cf_pages", "Cloudflare Pages"),
                ],
                default="ftp",
                max_length=20,
            ),
        ),
    ]
