# Generated by Django 5.1.4 on 2025-03-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyresult',
            name='achieved',
        ),
        migrations.AddField(
            model_name='keyresult',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
