# Generated by Django 5.1.4 on 2025-03-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_remove_keyresult_achieved_keyresult_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyresults', to='okr.objective'),
        ),
    ]
