# Generated by Django 5.1.4 on 2025-04-02 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0003_alter_keyresult_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.objective'),
        ),
    ]
