# Generated by Django 5.1.4 on 2025-04-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0006_epic_story_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='theme',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('red', 'Red'), ('gray', 'Gray')], default='gray', max_length=50),
        ),
    ]
