# Generated by Django 5.1.4 on 2025-04-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0008_entity_strategy_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
