# Generated by Django 6.0 on 2026-01-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0009_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable machine key, e.g. 'availability', 'latency'",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Availability'", max_length=120
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Reliability', 'Security', 'Adoption'",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="KeyResultMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("percent", "Percent"),
                            ("currency", "Currency"),
                            ("count", "Count"),
                            ("boolean", "Pass/Fail"),
                            ("score", "Score"),
                            ("text", "Text"),
                        ],
                        default="number",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ms, %, tickets, integrations",
                        max_length=30,
                    ),
                ),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("current_value", models.FloatField(blank=True, null=True)),
                ("threshold_green", models.FloatField(blank=True, null=True)),
                ("threshold_yellow", models.FloatField(blank=True, null=True)),
                ("threshold_red", models.FloatField(blank=True, null=True)),
                (
                    "polarity",
                    models.CharField(
                        choices=[
                            ("higher_is_better", "Higher is better"),
                            ("lower_is_better", "Lower is better"),
                            ("target_is_best", "Target is best"),
                        ],
                        default="higher_is_better",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0, help_text="Optional weight for rollups"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "key_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="okr.keyresult",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kr_metrics",
                        to="okr.metricdimension",
                    ),
                ),
            ],
            options={
                "ordering": ["dimension__sort_order", "dimension__name"],
                "unique_together": {("key_result", "dimension")},
            },
        ),
    ]
