# Generated by Django 6.0 on 2026-07-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarkdownDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1000, unique=True)),
                (
                    "project",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("rel_path", models.CharField(blank=True, default="", max_length=1000)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("mtime", models.DateTimeField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("pinned", models.BooleanField(default=False)),
                ("last_indexed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-pinned", "-mtime", "title"],
                "indexes": [
                    models.Index(
                        fields=["project", "-mtime"],
                        name="codex_markd_project_8ce56c_idx",
                    ),
                    models.Index(fields=["read"], name="codex_markd_read_f31ae0_idx"),
                ],
            },
        ),
    ]
