# Generated by Django 6.0 on 2026-06-14 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("internal", "Internal (Django/React)"),
                            ("loveable", "Loveable.com"),
                            ("other", "Other"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("provisioning", "Provisioning"),
                            ("deployed", "Deployed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, default="", max_length=700),
                ),
                ("repo_url", models.URLField(blank=True, default="")),
                (
                    "gcp_project_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "gcp_region",
                    models.CharField(blank=True, default="us-central1", max_length=60),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CloudResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("cloud_run", "Cloud Run service"),
                            ("cloud_sql", "Cloud SQL instance"),
                            ("storage_bucket", "Cloud Storage bucket"),
                            ("secret", "Secret Manager secret"),
                            ("artifact_repo", "Artifact Registry repo"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "identifier",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("deleted", "Deleted"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cloud_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="atlas.cloudproject",
                    ),
                ),
            ],
            options={
                "ordering": ["cloud_project", "resource_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["cloud_project", "resource_type"],
                        name="atlas_cloud_cloud_p_ff7de6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeploymentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("provision", "Provision"),
                            ("deploy", "Deploy"),
                            ("migrate", "Migrate"),
                            ("sync_status", "Sync status"),
                            ("teardown", "Teardown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("log", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cloud_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="atlas.cloudproject",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["cloud_project", "-started_at"],
                        name="atlas_deplo_cloud_p_2d6fad_idx",
                    )
                ],
            },
        ),
    ]
