# Generated by Django 6.0 on 2026-06-14 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                (
                    "account_login",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["account_login"],
            },
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="auto_deploy",
            field=models.BooleanField(
                default=False,
                help_text="Deploy automatically on push to the deploy branch.",
            ),
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="deploy_branch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Branch that triggers auto-deploy. Blank = match any branch's default.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="github_repo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="owner/name — used to match incoming push webhooks.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="github_installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="atlas.githubinstallation",
            ),
        ),
    ]
