# Generated by Django 6.0 on 2026-06-15 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0002_githubinstallation_cloudproject_auto_deploy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. the customer/org name.", max_length=200
                    ),
                ),
                (
                    "gcp_project_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default GCP project for this identity (overrides global GCP_PROJECT_ID).",
                        max_length=120,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("impersonate", "Impersonate service account"),
                            ("key_file", "Service account key file"),
                        ],
                        default="impersonate",
                        max_length=20,
                    ),
                ),
                (
                    "service_account_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="For impersonation: the SA to act as.",
                        max_length=254,
                    ),
                ),
                (
                    "key_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For key_file: absolute path to the SA JSON key on the server.",
                        max_length=700,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                help_text="Per-customer GCP identity. Blank = use the server's host identity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="atlas.cloudcredential",
            ),
        ),
    ]
