# Generated by Django 6.0 on 2026-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0003_cloudcredential_cloudproject_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudproject",
            name="hardened",
            field=models.BooleanField(
                default=False,
                help_text="Has this project been through the production hardening pass?",
            ),
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="hardened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cloudproject",
            name="hardened_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
