# Generated by Django 6.0 on 2026-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0004_cloudproject_hardened_cloudproject_hardened_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudproject",
            name="service_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cloud Run service name override. Blank = derived from the slug. Set this to target an existing service (e.g. 'dealermaster').",
                max_length=63,
            ),
        ),
    ]
