# Generated by Django 6.0 on 2026-07-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0005_cloudproject_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentrun",
            name="action",
            field=models.CharField(
                choices=[
                    ("provision", "Provision"),
                    ("pull", "Pull source"),
                    ("deploy", "Deploy"),
                    ("migrate", "Migrate"),
                    ("sync_status", "Sync status"),
                    ("teardown", "Teardown"),
                ],
                max_length=20,
            ),
        ),
    ]
