# Generated by Django 6.0 on 2026-06-26 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atlas", "0005_cloudproject_service_name"),
        ("sites_builder", "0023_site_nav_cta_label_site_nav_cta_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("summary", models.CharField(blank=True, default="", max_length=400)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("app", "App"),
                            ("website", "Website"),
                            ("experiment", "Experiment"),
                            ("tool", "Tool"),
                            ("external", "External"),
                        ],
                        default="app",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("building", "Building"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                ("repo_url", models.URLField(blank=True, default="")),
                ("live_url", models.URLField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atlas_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiatives",
                        to="atlas.cloudproject",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiatives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiatives",
                        to="sites_builder.site",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InitiativeUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("done", "Done"), ("next", "Next"), ("note", "Note")],
                        default="done",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "occurred_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="argus.initiative",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-occurred_on"],
                        name="argus_initi_kind_2f06c4_idx",
                    )
                ],
            },
        ),
    ]
