# Generated by Django 6.0 on 2025-12-16 23:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("okr", "0009_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "problem_statement",
                    models.TextField(
                        help_text="Use customer language. What pain exists?"
                    ),
                ),
                (
                    "target_customer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("validated", "Validated"),
                            ("killed", "Killed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "idea_type",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("adjacent", "Adjacent"),
                            ("longshot", "Long-shot"),
                        ],
                        default="adjacent",
                        max_length=20,
                    ),
                ),
                (
                    "founder_conviction",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Founder conviction 1–5 (explicit gut check).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("killed_reason", models.TextField(blank=True, default="")),
                ("killed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which business entity / venture this idea belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_ideas",
                        to="okr.entity",
                    ),
                ),
                (
                    "proposed_strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: existing Strategy this idea aligns to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_ideas",
                        to="okr.strategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField(help_text="We believe that…")),
                (
                    "must_be_true",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What must be true for this to work?",
                    ),
                ),
                (
                    "disproof",
                    models.TextField(
                        blank=True, default="", help_text="What would prove this wrong?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("supported", "Supported"),
                            ("disproven", "Disproven"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheses",
                        to="janus.idea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Graduation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="okr.objective",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="okr.strategy",
                    ),
                ),
                (
                    "idea",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation",
                        to="janus.idea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pain_intensity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "pain_frequency",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "capital_efficiency",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "strategic_leverage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "time_to_signal",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="janus.idea",
                    ),
                ),
            ],
            options={
                "ordering": ["-total", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationSprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("duration_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "budget_cap",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("required_interviews", models.PositiveSmallIntegerField(default=5)),
                (
                    "pain_threshold",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Minimum avg pain intensity (1–5) to pass the customer pain gate.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="janus.idea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("interview", "Customer Interview"),
                            ("loi", "LOI / Pilot Interest"),
                            ("survey", "Survey"),
                            ("other", "Other"),
                        ],
                        default="interview",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer_org",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quote",
                    models.TextField(
                        blank=True, default="", help_text="Direct quote (gold)."
                    ),
                ),
                ("summary", models.TextField(help_text="What was learned?")),
                (
                    "pain_intensity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1–5. Only required for interviews.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "pain_frequency",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1–5. How often does the pain occur?",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="janus.validationsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GateResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gate",
                    models.CharField(
                        choices=[
                            ("customer_pain", "Gate 1: Customer Pain"),
                            ("timebox", "Gate 2: Two-week Signal"),
                            ("budget", "Gate 2b: Budget Cap"),
                            ("portfolio", "Gate 3: Portfolio Rank (post-gate)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("rationale", models.TextField(blank=True, default="")),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="janus.idea",
                    ),
                ),
            ],
            options={
                "ordering": ["gate"],
                "unique_together": {("idea", "gate")},
            },
        ),
    ]
