# Generated by Django 6.0 on 2025-12-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hypothesis",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("non_negotiable", "Non-negotiable (Kill if false)"),
                    ("important", "Important"),
                    ("optional", "Optional"),
                ],
                default="important",
                help_text="If this is false, does the idea die?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hypothesis",
            name="risk_profile",
            field=models.CharField(
                choices=[("normal", "Normal"), ("longshot", "Long-shot")],
                default="normal",
                help_text="Is this a long-shot hypothesis?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hypothesis",
            name="validation_signals",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What evidence or signals would support this hypothesis?",
            ),
        ),
        migrations.AlterField(
            model_name="hypothesis",
            name="disproof",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hypothesis",
            name="must_be_true",
            field=models.TextField(blank=True, default=""),
        ),
    ]
