# Generated by Django 6.0 on 2025-12-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0004_seed_ifms_scorecoard"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorecardevaluation",
            name="hard_stop_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scorecardevaluation",
            name="hard_stop_triggered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scorecardevaluation",
            name="decision",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
