# Generated by Django 6.0 on 2026-02-04 03:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0005_scorecardevaluation_hard_stop_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DDSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["template", "order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScoreScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("min_value", models.IntegerField(default=0)),
                ("max_value", models.IntegerField(default=5)),
                ("labels_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DDCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("evidence_required", models.BooleanField(default=False)),
                ("non_negotiable", models.BooleanField(default=False)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("pass_threshold", models.IntegerField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="janus.ddsection",
                    ),
                ),
                (
                    "scoring_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criteria",
                        to="janus.scorescale",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="DDTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(default="v1", max_length=40)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"],
                        name="janus_ddtem_is_acti_3980ab_idx",
                    )
                ],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.AddField(
            model_name="ddsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="janus.ddtemplate",
            ),
        ),
        migrations.CreateModel(
            name="DueDiligenceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("complete", "Complete"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proceed", "Proceed"),
                            ("proceed_with_conditions", "Proceed With Conditions"),
                            ("pause", "Pause"),
                            ("walk_away", "Walk Away"),
                        ],
                        max_length=30,
                    ),
                ),
                ("verdict_rationale", models.TextField(blank=True)),
                ("promoted_to_execution", models.BooleanField(default=False)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dd_runs",
                        to="janus.ddtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DDRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("legal", "Legal"),
                            ("ops", "Operations"),
                            ("tech", "Technology"),
                            ("dependency", "Dependency"),
                            ("data", "Data"),
                            ("other", "Other"),
                        ],
                        default="tech",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "likelihood",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("risk_score", models.PositiveIntegerField(default=9)),
                ("mitigation_plan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("mitigating", "Mitigating"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("blocking", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_dd_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_criteria",
                    models.ManyToManyField(
                        blank=True, related_name="risks", to="janus.ddcriterion"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DDResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score_value", models.IntegerField()),
                (
                    "confidence",
                    models.CharField(
                        choices=[("low", "Low"), ("med", "Medium"), ("high", "High")],
                        default="med",
                        max_length=10,
                    ),
                ),
                ("commentary", models.TextField(blank=True)),
                (
                    "assessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "computed_weighted_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_dd_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="janus.ddcriterion",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DDPromotionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_context_label", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_dd_promotion_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_batches",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DDParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("reviewer", "Reviewer"),
                            ("security", "Security"),
                            ("architecture", "Architecture"),
                            ("ops", "Operations"),
                            ("legal", "Legal"),
                            ("observer", "Observer"),
                        ],
                        default="reviewer",
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("comment", "Comment"),
                            ("score", "Score"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="janus_dd_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DDEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("doc", "Document"),
                            ("link", "Link"),
                            ("screenshot", "Screenshot"),
                            ("repo_access", "Repo Access"),
                            ("interview", "Interview"),
                            ("other", "Other"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="janus.ddcriterion",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_dd_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="janus.ddsection",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DDCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("due_by", models.DateField(blank=True, null=True)),
                (
                    "must_complete_before",
                    models.CharField(
                        choices=[
                            ("signing", "Signing"),
                            ("closing", "Closing"),
                            ("post_close_30", "Post-close (30 days)"),
                            ("post_close_90", "Post-close (90 days)"),
                        ],
                        default="closing",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("waived", "Waived"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "mapped_risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conditions",
                        to="janus.ddrisk",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TargetCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("website", models.URLField(blank=True)),
                (
                    "deal_stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("loi", "LOI"),
                            ("diligence", "Diligence"),
                            ("definitive", "Definitive"),
                            ("closed", "Closed"),
                            ("dropped", "Dropped"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="janus_target_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="duediligencerun",
            name="target_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dd_runs",
                to="janus.targetcompany",
            ),
        ),
        migrations.CreateModel(
            name="DDPromotedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("risk", "Risk"),
                            ("condition", "Condition"),
                            ("criterion", "Criterion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("proposed_objective", models.CharField(max_length=300)),
                ("proposed_key_result", models.CharField(blank=True, max_length=400)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("med", "Medium"), ("high", "High")],
                        default="med",
                        max_length=10,
                    ),
                ),
                (
                    "okr_objective_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "okr_key_result_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="janus.ddpromotionbatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["batch", "source_type"],
                        name="janus_ddpro_batch_i_520303_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="janus_ddpro_source__d7bca8_idx",
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="ddsection",
            unique_together={("template", "title")},
        ),
        migrations.AddIndex(
            model_name="ddrisk",
            index=models.Index(
                fields=["run", "blocking", "status"],
                name="janus_ddris_run_id_e175e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ddrisk",
            index=models.Index(
                fields=["run", "category"], name="janus_ddris_run_id_00ef6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ddresponse",
            index=models.Index(
                fields=["run", "criterion"], name="janus_ddres_run_id_e11577_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ddresponse",
            constraint=models.UniqueConstraint(
                fields=("run", "criterion"), name="uniq_ddresponse_run_criterion"
            ),
        ),
        migrations.AddConstraint(
            model_name="ddparticipant",
            constraint=models.UniqueConstraint(
                fields=("run", "user"), name="uniq_ddparticipant_run_user"
            ),
        ),
        migrations.AddIndex(
            model_name="ddevidence",
            index=models.Index(
                fields=["run", "evidence_type"], name="janus_ddevi_run_id_02c6b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ddcriterion",
            unique_together={("section", "title")},
        ),
        migrations.AddIndex(
            model_name="duediligencerun",
            index=models.Index(
                fields=["status", "due_date"], name="janus_duedi_status_736764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="duediligencerun",
            index=models.Index(
                fields=["target_company", "status"],
                name="janus_duedi_target__3ed927_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="duediligencerun",
            unique_together={("target_company", "template", "round_number")},
        ),
    ]
