# Generated by Django 6.0 on 2026-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0006_ddsection_scorescale_ddcriterion_ddtemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddresponse",
            name="score_value",
            field=models.IntegerField(default=0),
        ),
    ]
