# Generated by Django 6.0 on 2026-02-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0007_alter_ddresponse_score_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="DDQuantitativeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics_as_of_date", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("low", "Low"), ("med", "Medium"), ("high", "High")],
                        default="med",
                        max_length=10,
                    ),
                ),
                ("source_notes", models.TextField(blank=True, default="")),
                ("total_customers", models.IntegerField(blank=True, null=True)),
                ("active_customers", models.IntegerField(blank=True, null=True)),
                (
                    "top_1_customer_pct_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "top_3_customer_pct_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "churn_rate_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "net_revenue_retention_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "win_rate_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("sales_cycle_days", models.IntegerField(blank=True, null=True)),
                (
                    "pipeline_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "revenue_ttm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "mrr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "arr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "gross_margin_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "operating_income_ttm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "burn_rate_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("runway_months", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="janus.duediligencerun",
                    ),
                ),
            ],
        ),
    ]
