# Generated by Django 6.0 on 2026-02-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0008_ddquantitativesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetcompany",
            name="long_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="targetcompany",
            name="long_description_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="targetcompany",
            name="short_description",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
    ]
