# Generated by Django 6.0 on 2026-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("janus", "0009_targetcompany_long_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetcompany",
            name="logo_file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Relative path under MEDIA_ROOT, e.g. company_logos/output.png",
                max_length=255,
            ),
        ),
    ]
