# Generated by Django 6.0 on 2025-12-21 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("root_path", models.CharField(max_length=512)),
                ("large_loc_threshold", models.PositiveIntegerField(default=50)),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("total_components", models.PositiveIntegerField(default=0)),
                ("duplicate_names_count", models.PositiveIntegerField(default=0)),
                ("large_components_count", models.PositiveIntegerField(default=0)),
                ("security_findings_count", models.PositiveIntegerField(default=0)),
                ("security_high_count", models.PositiveIntegerField(default=0)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ScannedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("path", models.CharField(max_length=700)),
                (
                    "project_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("components_count", models.PositiveIntegerField(default=0)),
                ("security_findings_count", models.PositiveIntegerField(default=0)),
                ("security_high_count", models.PositiveIntegerField(default=0)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                (
                    "scan_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="code_analyzer.scanrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.CharField(db_index=True, max_length=40)),
                (
                    "kind",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("LOW", "LOW"),
                            ("MED", "MED"),
                            ("HIGH", "HIGH"),
                        ],
                        db_index=True,
                        default="",
                        max_length=6,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("file", models.CharField(db_index=True, max_length=700)),
                ("lineno", models.PositiveIntegerField(blank=True, null=True)),
                ("loc", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_duplicate_name",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_large", models.BooleanField(db_index=True, default=False)),
                (
                    "scan_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="code_analyzer.scannedproject",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scan_project", "bucket"],
                        name="code_analyz_scan_pr_fd55af_idx",
                    ),
                    models.Index(
                        fields=["scan_project", "kind"],
                        name="code_analyz_scan_pr_e23b66_idx",
                    ),
                    models.Index(
                        fields=["scan_project", "severity"],
                        name="code_analyz_scan_pr_de68f0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="scannedproject",
            index=models.Index(
                fields=["scan_run", "name"], name="code_analyz_scan_ru_8e3887_idx"
            ),
        ),
    ]
