# Generated by Django 6.0 on 2026-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanitem",
            name="ai_confidence",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="scanitem",
            name="ai_explanation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="scanitem",
            name="ai_fix",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="scanitem",
            name="ai_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanitem",
            name="ai_verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("real", "Real"),
                    ("false_positive", "False positive"),
                    ("uncertain", "Uncertain"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scanitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirmed", "Confirmed"),
                    ("false_positive", "False positive"),
                    ("fixed", "Fixed"),
                    ("suppressed", "Suppressed"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
    ]
