"""
Django settings for fractals project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
SITES_OUTPUT_ROOT = Path(BASE_DIR) / "output" / "sites"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "http://localhost").split(",") if o.strip()]
# --- Code Analyzer settings ---
CODE_ANALYZER_ROOT = os.environ.get("CODE_ANALYZER_ROOT", str(BASE_DIR.parent))
CODE_ANALYZER_LARGE_LOC = 500
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
GA4_SERVICE_ACCOUNT_FILE = os.environ.get("GA4_SERVICE_ACCOUNT_FILE", "")
AGPAY_STRIPE_SECRET_KEY = os.environ.get("AGPAY_STRIPE_SECRET_KEY", "")
AGPAY_STRIPE_WEBHOOK_SECRET = os.environ.get("AGPAY_STRIPE_WEBHOOK_SECRET", "")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

# --- Atlas (cloud projects & migrations) ---
GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "")
GCP_REGION = os.environ.get("GCP_REGION", "us-central1")
# Where Atlas clones repos / stages source for builds.
# Atlas clones/git-syncs customer repos here. This MUST live OUTSIDE the Foundry
# git repo: a nested clone that lacks its own .git lets `git -C <clone> …`
# escalate to Foundry's .git and reset Foundry to a customer repo (this wiped
# Foundry twice on 2026-07-20/21). Keep it a sibling of the project.
ATLAS_WORK_ROOT = Path(BASE_DIR).parent / "_atlas_work"
ATLAS_BACKUP_ROOT = Path(BASE_DIR).parent / "_atlas_backups"
# Max seconds to wait for a Cloud Build + Cloud Run deploy.
ATLAS_DEPLOY_TIMEOUT = int(os.environ.get("ATLAS_DEPLOY_TIMEOUT", "1800"))
# When True, queued deploys are also processed inline in a background thread
# (zero-setup dev). Set False in production and run `manage.py atlas_worker`.
ATLAS_INLINE_WORKER = os.environ.get("ATLAS_INLINE_WORKER", "True") == "True"

# Atlas GitHub App (for webhook-driven auto-deploy)
GITHUB_APP_ID = os.environ.get("GITHUB_APP_ID", "")
GITHUB_APP_PRIVATE_KEY_PATH = os.environ.get("GITHUB_APP_PRIVATE_KEY_PATH", "")
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET", "")

# Aegis (public exposure monitoring). Falls back to a PAT when a watch profile
# has no GitHub App installation attached; needs only `public_repo` scope.
AEGIS_GITHUB_TOKEN = os.environ.get("AEGIS_GITHUB_TOKEN", "")
# GitHub's code_search bucket is ~10 req/min — 7s spacing keeps us under it.
AEGIS_SEARCH_MIN_INTERVAL = float(os.environ.get("AEGIS_SEARCH_MIN_INTERVAL", "7.0"))
# Per-run query cap. Each query costs ~7s, so 40 ≈ a 5 minute sweep.
AEGIS_MAX_QUERIES = int(os.environ.get("AEGIS_MAX_QUERIES", "40"))
AEGIS_MAX_BACKOFF = int(os.environ.get("AEGIS_MAX_BACKOFF", "120"))
# Crawler / dataset / mirror repos that index the whole web. A brand keyword
# matches these every time and buries real findings. Substring match on
# "owner/name", case-insensitive.
AEGIS_DEFAULT_REPO_DENYLIST = [
    "duckduckgo/tracker-radar",
    "tracker-radar",
    "privacy-policy-historical",
    "trackerradarapi",
    "public-suffix",
    "publicsuffix",
    "top-1m",
    "majestic-million",
    "tranco",
    "alexa-top",
    "domain-list",
    "domains-list",
    "url-list",
    "blocklist",
    "blacklist",
    "adblock",
    "easylist",
    "hosts-file",
    "hostsfile",
    "stevenblack/hosts",
    "phishing",
    "certstream",
    "crt.sh",
    "commoncrawl",
    "wayback",
    # URL/text corpora — surfaced by the first real global sweep (AMA, 2026-08).
    # A brand keyword matches these because they contain the whole web.
    "annotation-urls",
    "-corpus",
    "corpora",
    "citation-study",
    "web-archive",
    "webarchive",
    "gfw-report",
    "crawl",
    "scrape",
    "dataset",
]

MEDIA_URL = "/uploads/"
MEDIA_ROOT = BASE_DIR / "uploads"
FOUNDRY_HOME_CARDS = {
    "janus": True,
    "okr": True,
    "sites_builder": True,
    "code_analyzer": True,
    "athena": True,
    "hermes": True,
    "tasks": True,
    "mnemos": True,
    "atlas": True,
    "argus": True,
    "aegis": True,
    "codex": True,
}

# Codex (markdown library) — directories scanned for .md files.
MD_LIBRARY_ROOTS = [r"C:\Projects"]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "apps.common",
    "apps.sites_builder",
    "apps.code_analyzer",
    "apps.okr",
    "apps.janus.apps.JanusConfig",
    "apps.athena",
    "apps.hermes",
    "apps.task",
    "apps.mnemos.apps.MnemosConfig",
    "apps.atlas.apps.AtlasConfig",
    "apps.argus.apps.ArgusConfig",
    "apps.aegis.apps.AegisConfig",
    "apps.codex.apps.CodexConfig",
    "platform_apps.apps.tenants",
    "platform_apps.apps.agpay",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "foundry.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "foundry" / "templates"],  # global templates dir if you want one
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "foundry.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Find static files also in the project-level "static" folder
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Base URL where your built static sites are served for preview.
# For example, if you're serving C:\Projects\fractals\output\sites
# at http://localhost:63342/fractals/output/sites/, set:
# STATIC_SITE_PREVIEW_BASE_URL = "http://localhost:63342/fractals/output/sites"

STATIC_SITE_PREVIEW_BASE_URL = "http://localhost:63342/foundry/output/sites"  # fill this with your dev preview URL when ready
